// 国家代码映射表（访问规则 Geo 条目使用）
export const COUNTRY_CODES: Record<string, { name: string; flag: string }> = {
  CN: { name: '中国', flag: '🇨🇳' },
  US: { name: '美国', flag: '🇺🇸' },
  RU: { name: '俄罗斯', flag: '🇷🇺' },
  KP: { name: '朝鲜', flag: '🇰🇵' },
  KR: { name: '韩国', flag: '🇰🇷' },
  JP: { name: '日本', flag: '🇯🇵' },
  HK: { name: '香港', flag: '🇭🇰' },
  TW: { name: '台湾', flag: '🇹🇼' },
  SG: { name: '新加坡', flag: '🇸🇬' },
  DE: { name: '德国', flag: '🇩🇪' },
  FR: { name: '法国', flag: '🇫🇷' },
  GB: { name: '英国', flag: '🇬🇧' },
  AU: { name: '澳大利亚', flag: '🇦🇺' },
  CA: { name: '加拿大', flag: '🇨🇦' },
  IN: { name: '印度', flag: '🇮🇳' },
  BR: { name: '巴西', flag: '🇧🇷' },
  IT: { name: '意大利', flag: '🇮🇹' },
  ES: { name: '西班牙', flag: '🇪🇸' },
  NL: { name: '荷兰', flag: '🇳🇱' },
  UA: { name: '乌克兰', flag: '🇺🇦' },
  IR: { name: '伊朗', flag: '🇮🇷' },
  NG: { name: '尼日利亚', flag: '🇳🇬' },
  ZA: { name: '南非', flag: '🇿🇦' },
  TR: { name: '土耳其', flag: '🇹🇷' },
  SA: { name: '沙特阿拉伯', flag: '🇸🇦' },
  MX: { name: '墨西哥', flag: '🇲🇽' },
  ID: { name: '印度尼西亚', flag: '🇮🇩' },
  TH: { name: '泰国', flag: '🇹🇭' },
  VN: { name: '越南', flag: '🇻🇳' },
  MY: { name: '马来西亚', flag: '🇲🇾' },
  PH: { name: '菲律宾', flag: '🇵🇭' },
  AE: { name: '阿联酋', flag: '🇦🇪' },
  IL: { name: '以色列', flag: '🇮🇱' },
  PL: { name: '波兰', flag: '🇵🇱' },
  SE: { name: '瑞典', flag: '🇸🇪' },
  NO: { name: '挪威', flag: '🇳🇴' },
  CH: { name: '瑞士', flag: '🇨🇭' },
  BE: { name: '比利时', flag: '🇧🇪' },
  AT: { name: '奥地利', flag: '🇦🇹' },
  CZ: { name: '捷克', flag: '🇨🇿' },
  PT: { name: '葡萄牙', flag: '🇵🇹' },
  DK: { name: '丹麦', flag: '🇩🇰' },
  FI: { name: '芬兰', flag: '🇫🇮' },
  IE: { name: '爱尔兰', flag: '🇮🇪' },
  NZ: { name: '新西兰', flag: '🇳🇿' },
  AR: { name: '阿根廷', flag: '🇦🇷' },
  CL: { name: '智利', flag: '🇨🇱' },
  CO: { name: '哥伦比亚', flag: '🇨🇴' },
  EG: { name: '埃及', flag: '🇪🇬' },
  PK: { name: '巴基斯坦', flag: '🇵🇰' },
  BD: { name: '孟加拉', flag: '🇧🇩' },
}

export const getCountryInfo = (code: string) => {
  return COUNTRY_CODES[code] || { name: code, flag: '🏳️' }
}
